apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hackapp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: hackapp
      labels:
        app: hackapp
    spec:
      containers:
        - name: hackapp
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          image: gcr.io/$PROJECT_ID/some-hack:latest
